if [ "$XDG_SESSION_DESKTOP" = "gamescope" ] ; then
    SCREEN_WIDTH=2560
    SCREEN_HEIGHT=1440
    REFRESH_RATE=240
    CONNECTOR=DP-3
    CLIENTCMD="steam -gamepadui -pipewire-dmabuf"
    GAMESCOPECMD="/usr/bin/gamescope --hdr-enabled --force-windows-fullscreen --hdr-itm-enable \
    --hide-cursor-delay 3000 --fade-out-duration 200 --xwayland-count 2 \
    -w $SCREEN_WIDTH -h $SCREEN_HEIGHT \
    -W $SCREEN_WIDTH -H $SCREEN_HEIGHT -r $REFRESH_RATE -O $CONNECTOR"
fi
