[General]
closeToTray=true
networkCookies="@ByteArray(cc=U9LlUbc8p2B9K0V1kyGek0MZqufp78E8PxAGIZ2H+CdXnzOOLzoYPvnqfjv/XkmTj4Y=; HttpOnly; expires=Sat, 26-Jun-2027 03:17:55 GMT; domain=localhost; path=/\n)"
startInTray=true
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\xa0\0\0\0\0\0\0\n\x8d\0\0\x5\x87\0\0\x5\xa0\0\0\0\0\0\0\n\x8d\0\0\x5\x87\0\0\0\x1\0\0\0\0\n\0\0\0\x5\xa0\0\0\0\0\0\0\n\x8d\0\0\x5\x87)
zoomFactor=1
