[General]
closeToTray=false
networkCookies="@ByteArray(cc=U9LlUbc8p2B9K0V1kyGek0MZqufp78E8PxAGIZ2H+CdXnzOOLzoYPvnqfjv/XkmTj4Y=; HttpOnly; expires=Sat, 26-Jun-2027 03:17:55 GMT; domain=localhost; path=/\n)"
startInTray=false
startupDelay=0
zoomFactor=1
